# Generated by Django 3.2.2 on 2021-05-06 10:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MyPolls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 10, 13, 56, 632155, tzinfo=utc), verbose_name='Time published'),
        ),
    ]
